#ifndef GRABBER_H
#define GRABBER_H


#define GRABBER_STAGE_NETWORK "NETWORK"
#define GRABBER_STAGE_RENDER "RENDER"
#define GRABBER_STAGE_OUTPUT "OUTPUT"

#define GRABBER_DEBUG_NET_ERROR "NET_ERROR"
#define GRABBER_DEBUG_HTTP_ERROR "HTTP_ERROR"
#define GRABBER_DEBUG_TIMEOUT_ERROR "TIMEOUT_ERROR"
#define GRABBER_DEBUG_RENDER_ERROR "RENDER_ERROR"
#define GRABBER_DEBUG_OPTION_ERROR "OPTION_ERROR"

#endif // GRABBER_H
